/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package keeper;

import componentes2.HEditor;
import componentes2.HScrollPane;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur
 */
public class FrmPrincipal extends javax.swing.JFrame {

    public int abaAberta;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();

        adicionarAba();
    }

    public void adicionarAba() {

        HEditor editor = new HEditor();
        HScrollPane scroll = new HScrollPane(editor);
        
        editor.addPopupMenu(pppMenuEditor);
        
        jTabbedPane1.add("Aba " + (jTabbedPane1.getTabCount() + 1), editor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pppMenuEditor = new javax.swing.JPopupMenu();
        ItmNovaAba = new javax.swing.JMenuItem();
        ItmManterSobreJanelas = new javax.swing.JCheckBoxMenuItem();
        ItmRenomearAba = new javax.swing.JMenuItem();
        ItmRenomearJanela = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        ItmNovaAba.setText("Nova guia");
        ItmNovaAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmNovaAbaActionPerformed(evt);
            }
        });
        pppMenuEditor.add(ItmNovaAba);

        ItmManterSobreJanelas.setSelected(true);
        ItmManterSobreJanelas.setText("Manter o Keeper sobre as outras janelas");
        ItmManterSobreJanelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmManterSobreJanelasActionPerformed(evt);
            }
        });
        pppMenuEditor.add(ItmManterSobreJanelas);

        ItmRenomearAba.setText("Renomear Aba");
        ItmRenomearAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmRenomearAbaActionPerformed(evt);
            }
        });
        pppMenuEditor.add(ItmRenomearAba);

        ItmRenomearJanela.setText("Renomear Janela");
        ItmRenomearJanela.setToolTipText("");
        ItmRenomearJanela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItmRenomearJanelaActionPerformed(evt);
            }
        });
        pppMenuEditor.add(ItmRenomearJanela);

        jEditorPane1.setAutoscrolls(false);
        jEditorPane1.setComponentPopupMenu(pppMenuEditor);
        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Keeper (Beta)");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setComponentPopupMenu(pppMenuEditor);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTabbedPane1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ItmManterSobreJanelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmManterSobreJanelasActionPerformed
        this.setAlwaysOnTop(ItmManterSobreJanelas.isSelected());
    }//GEN-LAST:event_ItmManterSobreJanelasActionPerformed

    private void ItmNovaAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmNovaAbaActionPerformed
        adicionarAba();        
    }//GEN-LAST:event_ItmNovaAbaActionPerformed

    private void ItmRenomearAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmRenomearAbaActionPerformed
        String novoNome = JOptionPane.showInputDialog(this, "Qual o novo nome?");
        JOptionPane.showMessageDialog(this, "Desculpa, mas este recurso ainda não foi implementado.");
    }//GEN-LAST:event_ItmRenomearAbaActionPerformed

    private void ItmRenomearJanelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItmRenomearJanelaActionPerformed
        String novoNome = JOptionPane.showInputDialog(this, "Qual o novo nome?");
        this.setTitle(novoNome + " - Keeper");
    }//GEN-LAST:event_ItmRenomearJanelaActionPerformed

    private void jTabbedPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1PropertyChange
//
    }//GEN-LAST:event_jTabbedPane1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem ItmManterSobreJanelas;
    private javax.swing.JMenuItem ItmNovaAba;
    private javax.swing.JMenuItem ItmRenomearAba;
    private javax.swing.JMenuItem ItmRenomearJanela;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPopupMenu pppMenuEditor;
    // End of variables declaration//GEN-END:variables
}
